### ISSUE TITLE
Journal: next/previous links at the bottom of posts should respect the collection the current post is in

### ISSUE THREAD

**Issue by gldraphael** [TryGhost/Themes#246]
Let's assume we have the following in `routes.yaml`:

```yaml
collections:
  /french/:
    permalink: /french/{slug}/
    template: cuisine
    filter: tag:french
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-french
```

**Current behavior:**

The "Next Issue" and "Previous Issue" links do not respect the collection the current post belongs to. If the post belongs to the `french` collection, the "Next Issue" and "Previous Issue" links sometimes point to posts in the `/` collection.

**Expectation:**

1. For posts in the `french` collection: the "Next Issue" and "Previous Issue" links should only link to next/previous posts in the `french` collection.
2. For posts in the `/` collection: the "Next Issue" and "Previous Issue" links should link to posts that do not belong to the `french` collection.
